version: '3'
services:
  db:
    image: postgres:14
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql
    user: postgres
    environment:
      POSTGRES_DB: bootcamp_ruby_development
      POSTGRES_USER: bootcamp_ruby
      POSTGRES_PASSWORD: 1234
  web:
    depends_on: 
      - db
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment: 
      DATABASE_NAME: bootcamp_ruby_development
      DATABASE_USERNAME: bootcamp_ruby
      DATABASE_PASSWORD: 1234
      DATABASE_HOST: db
      DATABASE_PORT: 5432